
- name: MiMo-V2-Flash
  id: mimo-v2-flash
  max_context_length: 262000
- name: Devstral 2 2512
  id: devstral-2-2512
  max_context_length: 262000
- name: DeepSeek R1T2 Chimera
  id: deepseek-r1t2-chimera
  max_context_length: 164000
- name: DeepSeek V3.1 Nex N1
  id: deepseek-v3.1-nex-n1
  max_context_length: 131000
- name: DeepSeek R1T Chimera
  id: deepseek-r1t-chimera
  max_context_length: 164000
- name: Qwen3 Coder 480B A35B
  id: qwen3-coder-480b-a35b
  max_context_length: 262000
- name: Nemotron 3 Nano 30B A3B
  id: nemotron-3-nano-30b-a3b
  max_context_length: 256000
- name: Nemotron Nano 12B 2 VL
  id: nemotron-nano-12b-2-vl
  max_context_length: 128000
- name: GLM 4.5 Air
  id: glm-4.5-air
  max_context_length: 131000
- name: R1 0528
  id: r1-0528
  max_context_length: 164000
- name: R1T Chimera
  id: r1t-chimera
  max_context_length: 164000
- name: Gemma 3 27B
  id: gemma-3-27b
  max_context_length: 131000
- name: Llama 3.3 70B Instruct
  id: llama-3.3-70b-instruct
  max_context_length: 131000
- name: Venice Uncensored
  id: venice-uncensored
  max_context_length: 33000
- name: Gemini 2.0 Flash Experimental
  id: gemini-2.0-flash-experimental
  max_context_length: 1050000
- name: gpt-oss-120b
  id: gpt-oss-120b
  max_context_length: 131000
- name: Hermes 3 405B Instruct
  id: hermes-3-405b-instruct
  max_context_length: 131000
- name: Mistral 7B Instruct
  id: mistral-7b-instruct
  max_context_length: 33000
- name: gpt-oss-20b
  id: gpt-oss-20b
  max_context_length: 131000
- name: Mistral Small 3.1 24B
  id: mistral-small-3.1-24b
  max_context_length: 128000
- name: Llama 3.1 405B Instruct
  id: llama-3.1-405b-instruct
  max_context_length: 131000
- name: Nemotron Nano 9B V2
  id: nemotron-nano-9b-v2
  max_context_length: 128000
- name: Trinity Mini
  id: trinity-mini
  max_context_length: 131000
- name: Llama 3.2 3B Instruct
  id: llama-3.2-3b-instruct
  max_context_length: 131000
- name: Qwen3 4B
  id: qwen3-4b
  max_context_length: 41000
- name: Qwen2.5-VL 7B Instruct
  id: qwen2.5-vl-7b-instruct
  max_context_length: 33000
- name: Gemma 3n 2B
  id: gemma-3n-2b
  max_context_length: 8000
- name: Gemma 3 4B
  id: gemma-3-4b
  max_context_length: 33000
- name: Gemma 3 12B
  id: gemma-3-12b
  max_context_length: 33000
- name: Gemma 3n 4B
  id: gemma-3n-4b
  max_context_length: 8000
- name: Kimi K2 0711
  id: kimi-k2-0711
  max_context_length: 33000